FROM python:3.13.5

WORKDIR /app

# Copy requirements first for better caching
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Python entry point
ENTRYPOINT ["python"]